/* This file is auto-generated by src/loader/scripts/meta_join.py */

YUI().use(function(Y) {
   var CONFIG = {
      groups: {
         'inputex': {
            base: 'inputex/src/',
            combine: false,
            modules: { /* METAGEN */ }
         }
      }
   };

   if(typeof YUI_config === 'undefined') { 
      YUI_config = {groups: {}}; 
   }
   
   Y.mix(YUI_config.groups, CONFIG.groups);

});

